/** @type {import('@bacons/apple-targets/app.plugin').ConfigFunction} */
module.exports = config => ({
  type: "widget",
  icon: 'https://github.com/expo.png',
  entitlements: { /* Add entitlements */ },
  images: {
    // Festivals
    "akshaya_tritiya": "./assets/akshaya_tritiya.png",
    "bhaiya_dooj": "./assets/bhaiya_dooj.png",
    "dhanteras": "./assets/dhanteras.png",
    "diwali": "./assets/diwali.png",
    "dussehra": "./assets/dussehra.png",
    "ganesh_chaturthi": "./assets/ganesh_chaturthi.png",
    "govardhana_puja": "./assets/govardhana_puja.png",
    "guru_purnima": "./assets/guru_purnima.png",
    "hanuman_jayanti": "./assets/hanuman_jayanti.png",
    "holi": "./assets/holi.png",
    "karwa_chauth": "./assets/karwa_chauth.png",
    "kojagara_puja": "./assets/kojagara_puja.png",
    "krishna_janmashtami": "./assets/krishna_janmashtami.png",
    "lakshmi_puja": "./assets/lakshmi_puja.png",
    "maha_navami": "./assets/maha_navami.png",
    "maha_shivaratri": "./assets/maha_shivaratri.png",
    "makar_sankranti": "./assets/makar_sankranti.png",
    "naga_panchami": "./assets/naga_panchami.png",
    "narak_chaturdashi": "./assets/narak_chaturdashi.png",
    "raksha_bandhan": "./assets/raksha_bandhan.png",
    "rama_navami": "./assets/rama_navami.png",
    "rath_yatra": "./assets/rath_yatra.png",
    "ugadi": "./assets/ugadi.png",
    "vasant_panchami": "./assets/vasant_panchami.png",
    "vat_savitri": "./assets/vat_savitri.png",
    // Moon phases - Shukla
    "shukla_pratipada": "./assets/shukla_pratipada.png",
    "shukla_dwitiya": "./assets/shukla_dwitiya.png",
    "shukla_tritiya": "./assets/shukla_tritiya.png",
    "shukla_chaturthi": "./assets/shukla_chaturthi.png",
    "shukla_panchami": "./assets/shukla_panchami.png",
    "shukla_shashti": "./assets/shukla_shashti.png",
    "shukla_saptami": "./assets/shukla_saptami.png",
    "shukla_ashtami": "./assets/shukla_ashtami.png",
    "shukla_navami": "./assets/shukla_navami.png",
    "shukla_dashami": "./assets/shukla_dashami.png",
    "shukla_ekadashi": "./assets/shukla_ekadashi.png",
    "shukla_dwadashi": "./assets/shukla_dwadashi.png",
    "shukla_trayodashi": "./assets/shukla_trayodashi.png",
    "shukla_chaturdashi": "./assets/shukla_chaturdashi.png",
    "purnima": "./assets/purnima.png",
    // Moon phases - Krishna
    "krishna_pratipada": "./assets/krishna_pratipada.png",
    "krishna_dwitiya": "./assets/krishna_dwitiya.png",
    "krishna_tritiya": "./assets/krishna_tritiya.png",
    "krishna_chaturthi": "./assets/krishna_chaturthi.png",
    "krishna_panchami": "./assets/krishna_panchami.png",
    "krishna_shashti": "./assets/krishna_shashti.png",
    "krishna_saptami": "./assets/krishna_saptami.png",
    "krishna_ashtami": "./assets/krishna_ashtami.png",
    "krishna_navami": "./assets/krishna_navami.png",
    "krishna_dashami": "./assets/krishna_dashami.png",
    "krishna_ekadashi": "./assets/krishna_ekadashi.png",
    "krishna_dwadashi": "./assets/krishna_dwadashi.png",
    "krishna_trayodashi": "./assets/krishna_trayodashi.png",
    "krishna_chaturdashi": "./assets/krishna_chaturdashi.png",
    "amavasya": "./assets/amavasya.png"
  }
});